import React from 'react'
import { columns, StudentData } from '@/components/ui/data-table/columns'
import { DataTable } from '@/components/ui/data-table/data-table'

async function getData(): Promise<StudentData[]> {
    return [
        {
            id: "728ed52f",
            schooldId: "123456",
            fullName: "John Doe",
            level: 1,
            department: "Computer Science",
            address: "123 Main St",
            status: "active",
            email: "m@example.com",
        },
        {
            id: "a12bc34d",
            schooldId: "654321",
            fullName: "Jane Smith",
            level: 2,
            department: "Mathematics",
            address: "456 Oak Ave",
            status: "inactive",
            email: "jane.smith@example.com",
        },
        {
            id: "ff98aa77",
            schooldId: "112233",
            fullName: "Michael Johnson",
            level: 3,
            department: "Physics",
            address: "789 Pine Rd",
            status: "active",
            email: "michael.johnson@example.com",
        },
        {
            id: "0e1f2a3b",
            schooldId: "998877",
            fullName: "Emily Davis",
            level: 4,
            department: "Chemistry",
            address: "321 Maple Blvd",
            status: "graduated",
            email: "emily.davis@example.com",
        },
        {
            id: "bb44cc55",
            schooldId: "445566",
            fullName: "David Wilson",
            level: 1,
            department: "Biology",
            address: "147 Birch Ln",
            status: "active",
            email: "david.wilson@example.com",
        },
        {
            id: "cc33dd66",
            schooldId: "778899",
            fullName: "Sarah Martinez",
            level: 2,
            department: "Economics",
            address: "258 Cedar Dr",
            status: "suspended",
            email: "sarah.martinez@example.com",
        },
        {
            id: "dd77ee88",
            schooldId: "334455",
            fullName: "Robert Brown",
            level: 3,
            department: "History",
            address: "369 Willow St",
            status: "active",
            email: "robert.brown@example.com",
        },
        {
            id: "ee99ff00",
            schooldId: "221100",
            fullName: "Laura Garcia",
            level: 4,
            department: "Philosophy",
            address: "951 Aspen Ct",
            status: "inactive",
            email: "laura.garcia@example.com",
        },
        {
            id: "1122aa33",
            schooldId: "667788",
            fullName: "James Lee",
            level: 1,
            department: "Engineering",
            address: "753 Walnut Way",
            status: "active",
            email: "james.lee@example.com",
        },
        {
            id: "4455bb66",
            schooldId: "990011",
            fullName: "Olivia Harris",
            level: 2,
            department: "Political Science",
            address: "852 Chestnut Pl",
            status: "graduated",
            email: "olivia.harris@example.com",
        },
        {
            id: "7788cc99",
            schooldId: "120045",
            fullName: "William Clark",
            level: 3,
            department: "Sociology",
            address: "14 Elm St",
            status: "active",
            email: "william.clark@example.com",
        },
        {
            id: "8899dd00",
            schooldId: "564738",
            fullName: "Sophia Lewis",
            level: 1,
            department: "Art",
            address: "27 Magnolia Ave",
            status: "inactive",
            email: "sophia.lewis@example.com",
        },
        {
            id: "9900ee11",
            schooldId: "879654",
            fullName: "Benjamin Hall",
            level: 4,
            department: "Geography",
            address: "65 Spruce Rd",
            status: "graduated",
            email: "benjamin.hall@example.com",
        },
        {
            id: "aa11ff22",
            schooldId: "456123",
            fullName: "Amelia Young",
            level: 2,
            department: "English Literature",
            address: "38 Poplar Dr",
            status: "active",
            email: "amelia.young@example.com",
        },
        {
            id: "bb22gg33",
            schooldId: "741852",
            fullName: "Daniel Hernandez",
            level: 3,
            department: "Business Administration",
            address: "92 Redwood Blvd",
            status: "active",
            email: "daniel.hernandez@example.com",
        },
        {
            id: "cc33hh44",
            schooldId: "963852",
            fullName: "Chloe King",
            level: 1,
            department: "Psychology",
            address: "57 Cypress Ln",
            status: "suspended",
            email: "chloe.king@example.com",
        },
        {
            id: "dd44ii55",
            schooldId: "159357",
            fullName: "Matthew Scott",
            level: 2,
            department: "Music",
            address: "101 Palm St",
            status: "active",
            email: "matthew.scott@example.com",
        },
        {
            id: "ee55jj66",
            schooldId: "753951",
            fullName: "Ella Robinson",
            level: 3,
            department: "Anthropology",
            address: "202 Cypress Ave",
            status: "inactive",
            email: "ella.robinson@example.com",
        },
        {
            id: "ff66kk77",
            schooldId: "852456",
            fullName: "Alexander Walker",
            level: 4,
            department: "Law",
            address: "305 Sycamore Ct",
            status: "graduated",
            email: "alexander.walker@example.com",
        },
        {
            id: "gg77ll88",
            schooldId: "357159",
            fullName: "Mia Allen",
            level: 1,
            department: "Architecture",
            address: "412 Hickory Pl",
            status: "active",
            email: "mia.allen@example.com",
        }
    ]

}

async function Page() {
    const data = await getData()
    return (
        <div className="container mx-auto py-10">
            <DataTable columns={columns} data={data} />
        </div>
    )
}

export default Page